package com.github.nankotsu029.landformcraft.model;

public enum GenerationStage {
    QUEUED,
    VALIDATING_REQUEST,
    CALLING_AI,
    VALIDATING_INTENT,
    COMPILING_BLUEPRINT,
    GENERATING_LAYOUT,
    GENERATING_TERRAIN,
    GENERATING_FEATURES,
    GENERATING_STRUCTURES,
    VALIDATING_RESULT,
    RENDERING_PREVIEWS,
    EXPORTING_TILES,
    PACKAGING,
    READY,
    RECOVERY_REQUIRED,
    FAILED,
    CANCELLED
}
