package com.github.nankotsu029.landformcraft.core.v2.placement.apply;

public enum PlacementApplyFailureCodeV2 {
    SERVICE_CLOSED,
    QUEUE_SATURATED,
    STATE_MISMATCH,
    RELEASE_VERIFICATION_FAILED,
    BINDING_MISMATCH,
    CONFIRMATION_NOT_CONSUMED,
    SNAPSHOT_VERIFICATION_FAILED,
    CONTAINMENT_INVALID,
    SOURCE_INVALID,
    RESOURCE_BUDGET_EXCEEDED,
    CANCELLED_BEFORE_COMMIT,
    CANCELLED_AFTER_COMMIT,
    JOURNAL_PERSISTENCE_FAILED,
    GATEWAY_FAILURE,
    GATEWAY_RECEIPT_INVALID,
    SHUTDOWN_AFTER_COMMIT
}
