package com.github.nankotsu029.landformcraft.ai.spi.v2;

public enum DesignFailureCodeV2 {
    UNKNOWN_INTENT_VERSION,
    UNKNOWN_CAPABILITY,
    UNSUPPORTED_PROVIDER,
    UNSUPPORTED_MODEL,
    UNSUPPORTED_CAPABILITY,
    CAPABILITY_MISMATCH,
    INVALID_REQUEST,
    INVALID_RESPONSE,
    PATH_SECURITY,
    BUDGET_EXCEEDED,
    SECRET_REDACTION,
    DRAFT_NOT_CONFIRMED,
    HARD_PROMOTION_FORBIDDEN,
    PROVIDER_TRANSPORT
}
